version: "3"
services:
  backend:
    image: siddhant1178/fusionpact-backend:latest
    container_name: backend_app
    ports:
      - "8000:8000"

  frontend:
    image: siddhant1178/fusionpact-frontend:latest
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - backend
