name: Build-Test-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Step 1: Validate Secrets Exist
      - name: Validate Secrets
        run: |
          echo "🔍 Checking required secrets..."
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "❌ Missing DOCKER_USERNAME secret!"; exit 1;
          fi
          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "❌ Missing DOCKER_PASSWORD secret!"; exit 1;
          fi
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "❌ Missing EC2_HOST secret!"; exit 1;
          fi
          if [ -z "${{ secrets.EC2_USER }}" ]; then
            echo "❌ Missing EC2_USER secret!"; exit 1;
          fi
          if [ -z "${{ secrets.EC2_KEY }}" ]; then
            echo "❌ Missing EC2_KEY secret!"; exit 1;
          fi
          echo "✅ All required secrets are present."

      # ✅ Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Step 3: Build and Push Backend Image
      - name: Build and Push Backend Image
        run: |
          echo "🚀 Building backend image..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fusionpact-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/fusionpact-backend:latest

      # ✅ Step 4: Build and Push Frontend Image
      - name: Build and Push Frontend Image
        run: |
          echo "🚀 Building frontend image..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fusionpact-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/fusionpact-frontend:latest

      # ✅ Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "🧹 Cleaning up old containers..."
            cd fusionpact-devops-challenge || git clone https://github.com/siddhant0205/fusionpact-devops-challenge.git && cd fusionpact-devops-challenge
            git pull origin main
            docker compose down
            docker compose pull
            docker compose up -d
            docker system prune -f
            echo "✅ Deployment completed successfully!"

